apiVersion: federation.symphony/v1
kind: CatalogContainer
metadata:
  name: reefer-truck
spec:  
---
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: reefer-truck-v-v1
spec: 
  rootResource: reefer-truck
  catalogType: target
  properties:
    spec: 
      displayName: reefer-truck
      topologies:
      - bindings:
        - role: instance
          provider: providers.target.mqtt
          config:
            name: mqtt-proxy
            brokerAddress: tcp://mosquitto-service:1883
            clientID: office-1
            requestTopic: coa-request
            responseTopic: coa-response
            timeoutSeconds: 30
      properties:
        driver: mike
        capacity: 100
        temperature: -18
        weight: 1000
        fuel: 100
        status: available
        location: 0,0
        destination: 0,0  
        